### ISSUE TITLE
how to use it in container or k8s pod

### ISSUE THREAD

**Issue by law-lee** [hengyoush/kyanos#134]
mostly i can only login to a container or k8s pod. when start it, there is no data captured like below:
![image](https://github.com/user-attachments/assets/aadfddcd-6a6e-41e8-b8dd-de9a2a23a10d)

when push q, error returns:
![image](https://github.com/user-attachments/assets/f0f97c97-2b3e-441e-8449-862a41c7bdfa)

**Comment by hengyoush** [comment]
Currently, Kyanos can only run in privileged mode (--privileged) in containers/Pods.

**Comment by law-lee** [comment]
got it, thank for reply!
