### ISSUE TITLE
5.4.x 运行报错

### ISSUE THREAD

**Issue by xj1988** [hengyoush/kyanos#159]
[bs@VM-1-46-tencentos /opt/kyanos]$ ./kyanos watch http
                                  
  ⣻ 🦜 Kyanos Loading...                                                                                                      
  Kyanos exited.                                
                                                
  ..............................                
  ..............................                
  ..............................                
  🍩 Kyanos starting... 1ns                     
  🍎 Loaded eBPF maps & programs. 184.972835ms  
                                                
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0x7a222e]

goroutine 1 [running]:
kyanos/bpf.(*AgentObjects).Close(0x7f5a877cf108?)
        /home/runner/work/kyanos/kyanos/bpf/agent_x86_bpfel.go:327 +0xe
kyanos/bpf/loader.(*BPF).Close(0xc00004e0d0)
        /home/runner/work/kyanos/kyanos/bpf/loader/loader.go:33 +0x25
kyanos/agent.SetupAgent.func4()
        /home/runner/work/kyanos/kyanos/agent/agent.go:116 +0x17
kyanos/agent.SetupAgent({0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, {0x17f2880, ...}, ...})
        /home/runner/work/kyanos/kyanos/agent/agent.go:149 +0x8c3
kyanos/cmd.startAgent()
        /home/runner/work/kyanos/kyanos/cmd/common.go:99 +0x5dd
kyanos/cmd.init.func1(0xc000348f08, {0x14f5323?, 0x4?, 0x14f51c3?})
        /home/runner/work/kyanos/kyanos/cmd/http.go:32 +0x26f
github.com/spf13/cobra.(*Command).execute(0xc000348f08, {0x24cc800, 0x0, 0x0})
        /home/runner/go/pkg/mod/github.com/spf13/cobra@v1.8.1/command.go:989 +0xa91
github.com/spf13/cobra.(*Command).ExecuteC(0x2185e60)
        /home/runner/go/pkg/mod/github.com/spf13/cobra@v1.8.1/command.go:1117 +0x3ff
github.com/spf13/cobra.(*Command).Execute(...)
        /home/runner/go/pkg/mod/github.com/spf13/cobra@v1.8.1/command.go:1041
kyanos/cmd.Execute()
        /home/runner/work/kyanos/kyanos/cmd/root.go:114 +0x1a
main.main()
        /home/runner/work/kyanos/kyanos/main.go:6 +0xf
        
  执行命令后没有捕获到任何数据，退出后报错了，打印的日志如上。
  内核版本如下：
  [bs@VM-1-46-tencentos /opt/kyanos]$ uname -a
  Linux VM-1-46-tencentos 5.4.119-19.0009.44 #1 SMP Tue May 7 20:09:33 CST 2024 x86_64 x86_64 x86_64 GNU/Linux

**Comment by hengyoush** [comment]
Thank you for your feedback! 

There are two problems here:
1. when you execute `kyanos watch http`, no output display
2. when you exit, kyanos panic.

the panic problem seems a memory issue, i will take a look, but the first problem is strange, I tested kyanos with your kernel version(tencentos,  5.4.119-19.0009.44) , but it works fine. 
![demo](https://github.com/user-attachments/assets/a19b7a5c-b406-49bd-8ce9-17668ea4d747)

When you execute `kyanos watch http`, don't exit, does it display the following table:
<img width="1123" alt="image" src="https://github.com/user-attachments/assets/06472a3d-a394-4385-a18c-4861b4476153">
or any other error log?

if the table displayed, then open another shell, execute `curl http://www.baidu.com`, the table should display a record.

**Comment by xj1988** [comment]
执行 kyanos watch http 后一直卡在这个页面。
![微信截图_20241211125313](https://github.com/user-attachments/assets/eeaa3b50-d934-4276-9061-71e31e96db32)

执行 ctrl+c后出现了这个表格。
![微信截图_20241211125426](https://github.com/user-attachments/assets/d21cb79f-ec29-41b1-8eee-303742cab904)

即使手动 curl http://www.baidu.com，也没捕获到请求。

再次执行 ctrl+c 后就出现了上次评论的异常。

**Comment by xj1988** [comment]
1、执行 kyanos watch http 后一直卡在这里。

[bs@VM-1-46-tencentos /opt/kyanos]$ ./kyanos watch http
                                  
  ⣻ 🦜 Kyanos Loading...                                                                                                      
  ⣟ 🦜 Kyanos Loading...                        
                                                
  ..............................                
  ..............................                
  ..............................                
  🍩 Kyanos starting... 1ns                     
  🍎 Loaded eBPF maps & programs. 160.340442ms  
                                                
  Press ctrl+c to exit

2、执行 ctrl+c 后出现表格

⣷  Events received: 0/100

┌─────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────┐
│ id     StartTime   Connection                                Proto   TotalTime   ReqSize     RespSize    Net/Internal   ReadSocketTime  │
│─────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────│
│                                                                                                                                         │
│                                                                                                                                         │
│                                                                                                                                         │
│                                                                                                                                         │
│                                                                                                                                         │
│                                                                                                                                         │
└─────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────┘
  ↑/k up • ↓/j down

3、再次执行后出现上次评论的异常信息。

**Comment by hengyoush** [comment]
Can you execute  this command: `./kyanos watch http --debug`, and give me the log file: `/tmp/kyanos_xxx.log`?  
Thanks!

**Comment by hengyoush** [comment]
Oh, you should add `sudo`  before your command like `sudo ./kyanos watch http` !  @xj1988

**Comment by xj1988** [comment]
谢谢，可以了

**Comment by xj1988** [comment]
有两个其他的问题（ps：ip进行了脱敏）

1、
 ⢿  Events received: 100/100

┌──────────────────────────────────────────────────────────────────────────────
│ id     StartTime     Connection                                Proto   TotalTime   ReqSize     RespSize    Net/Internal   ReadSocketTi
│──────────────────────────────────────────────────────────────────────────────
│ 1      15:03:40.607  172.9.2.46:50802 => 151.241.97.138:80     HTTP    403.90      717         7           403.55         529.18      
│ 2      15:03:40.979  172.9.2.46:50716 => 151.241.97.138:80     HTTP    995.19      757         7           -              -           
│ 3      15:03:41.081  172.9.2.46:51378 => 151.241.97.138:80     HTTP    837.93      781         1154        837.87         879.65      
│ 4      15:03:41.687  172.9.2.46:50746 => 151.241.97.138:80     HTTP    365.10      753         7           365.06         438.59      
│ 5      15:03:40.404  172.9.2.46:51078 => 151.241.97.138:80     HTTP    2091.59     753         1434        2091.50        593.90      
│ 6      15:03:42.389  172.9.2.46:50746 => 151.241.97.138:80     HTTP    815.60      701         2947        815.30         956.53      
└──────────────────────────────────────────────────────────────────────────────
  ↑/k up • ↓/j down
  
  Net/Internal   ReadSocketTime 为横线的请求我查看应用日志，是进行了网络请求的。
  
  2、
╭───────────────────────────────╮                                                                                                       
│ Record Detail: 1 (Total: 100) 
╰───────────────────────────────╯                                                                                                       
                                        +-------------------+   +---------------------+                                                 
                                        | Process(pid:6493) |   | eth0(used:1175.35ms)|                                                 
                                        |                   --->|                     |                                                 
                                        +-------------------+   +---------------------+                                                 
                                                                           |                                                            
                                                                           |                                                            
                                                                           |                                                            
                                                                           v                                                            
  +-------------------------+     +------------------------+    +---------------------+                                                 
  | Process(used:1112.93ms) |     | Socket(used:1112.55ms) |    | eth0(used:-476.11ms)|                                                 
  |                         |<--- |                        |<---|                     |                                                 
  +-------------------------+     +------------------------+    +---------------------+                                                 
                                                                                                                                        
++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++
                                                                                                                                        
[conn] [pid=6493][local addr]=172.9.2.46:50936 [remote addr]=151.241.97.138:80 [side]=client [ssl]=false                                
[total duration] = 699.685(ms)(start=2024-12-12 15:04:06.407, end=2024-12-12 15:04:07.107) 

这里响应到网卡的耗时为什么会是负数？

**Comment by hengyoush** [comment]
1. "-" means some trace data is missing, so the time spent here can't be calculated. This usually happens with short-lived connections, connection closed before kyanos capture trace data.
2. This is a bug. Please download the v1.4.2 release, which hopefully fixes this problem.
@xj1988
