### ISSUE TITLE
Add build test workflow

### ISSUE THREAD

**Issue by hengyoush** [hengyoush/kyanos#176]
**Is your feature request related to a problem? Please describe.**
Add build test in workflow, ensure build steps in COMPILATION.md can work.

**Describe the solution you'd like**
Add a workflow file in .github/workflows

**Comment by spencercjh** [comment]
Could you let me know if you've started this yet?

I'm more than happy to contribute.

**Comment by hengyoush** [comment]
> Could you let me know if you've started this yet?
> 
> I'm more than happy to contribute.

No, I haven't started this yet. Your contribution is welcome! @spencercjh
