### ISSUE TITLE
Welcome to join the WeChat group / 欢迎加入微信群

### ISSUE THREAD

**Issue by hengyoush** [hengyoush/kyanos#178]
- 我的微信：hengyh1995，备注请注明："申请加入kyanos交流群"
- 直接扫码加群 ![image](https://github.com/user-attachments/assets/f0ea4c08-ae8a-4d0d-99a8-bbd1a9376cb3)

**Comment by ringbuffer0** [comment]
二维码过期了，求更新~

**Comment by a95241815** [comment]
过期了

**Comment by hengyoush** [comment]
> 过期了

update

**Comment by GoldenMan-Zia** [comment]
Expired

**Comment by ymygogogo** [comment]
Expired @hengyoush
