### ISSUE TITLE
Confirm the meanings of RemoteIp and LocalIp in Kyanos

### ISSUE THREAD

**Issue by sologgfun** [hengyoush/kyanos#185]
**Describe the bug**
When I use Kyanos for cluster-level traffic capture, I treat the localip as the initiator of the request and the remoteip as the recipient of the request. However, I found that the traffic doesn't match my expectations, and the tcpdump capture is match my expectations."

**To Reproduce**
Make a request to a NodePort-type service on node A in the cluster（IPVS MODE）, with the pod located on node B.

**Expected behavior**
In theory, the traffic should be:
Traffic from A to node B.
Traffic from B to the pod.

**Screenshots**
<img width="491" alt="image" src="https://github.com/user-attachments/assets/3f11215e-8730-4282-996e-14f50bdb5649" />
This shows a screenshot of Kyanos data for cluster B and the pod.
172.x.x.136 is the pod's IP, which Kyanos captures as localAddr, while the node IP 192.16.0.42 is captured as remoteAddr.

Below is the tcpdump screenshot:
<img width="1081" alt="image" src="https://github.com/user-attachments/assets/6bf168ad-c126-4e0b-be22-5498a02542d6" />
Based on my understanding, if localAddr is the initiator and remoteAddr is the receiver, then the direction in the tcpdump capture seems reversed.

**Information (please complete the following information):**
 - OS: [e.g. use `uname -ar`]

**Comment by hengyoush** [comment]
Thanks for the feedback!
In the first screenshot, where the traffic been captured, in node A or B?

**Comment by sologgfun** [comment]
> Thanks for the feedback! I have some questions:
> 
> 1. 172.x.x.136 is the ip of pod at A or B?
> 2. 192.16.0.42  is the ip of A or B?
> 3. Where the traffic been captured, in node A or B in first screenshot?

1. 172.x.x.136 is the ip of pod at B.
2. 192.16.0.42 is the ip of B.
3. 2pics capture traffic is same at B.

**Comment by hengyoush** [comment]
What the IPVS forwarding method do you use? (ipip or NAT or direct routing)

**Comment by hengyoush** [comment]
Because Kyanos successfully parsed the HTTP request in the system call of pod B's process, Kyanos captures the traffic with pod B's process as the local endpoint, and the host machine where the pod resides as the requesting endpoint.

Additionally what IPVS forwarding method do you use? (ipip or NAT or direct routing)

**Comment by sologgfun** [comment]
Do you mean that localip and remoteip don't indicate the direction of traffic? I think their meaning is a bit unclear. 
For example, when we mentioned where Kyanos captures traffic, traffic always has a direction, doesn't it? If the diff between localip and remote is not direction,then what is the diff?
Of course,Thanks for your reply and  I'll check the meaning of the `AnnotatedRecord.ConnDesc.Side` field later. 
By the way, my cluster is `BGP` , IPVS forwarding method is `NAT/Masquerade`.
<img width="546" alt="image" src="https://github.com/user-attachments/assets/530dac96-82fd-4372-a979-3e54350ae70f" />

**Comment by hengyoush** [comment]
>  localip and remoteip don't indicate the direction of traffic
Yes, this is true.

For example, you send a requests from a (ip:10.0.0.1) to b(ip: 10.0.0.2).
if you executed kyanos at a, then kyanos will reports 10.0.0.1 as local ip , 10.0.0.2 is remote, the `side` is client.
if you executed kyanos at b, then kyanos will reports 10.0.0.1 as remote ip , 10.0.0.2 is local, the `side` is server.

**Comment by sologgfun** [comment]
Okay, I understand now. Thank you very much! 😄
