### ISSUE TITLE
The current implementation of Is256ColorsSupported check is way too naive


### ISSUE THREAD

**Issue by ccoVeille** [hengyoush/kyanos#186]
https://github.com/hengyoush/kyanos/blob/c2e4d216a94d2983c888b2c62fab925972d59e09/common/term.go#L8-11

Take a look at project that could help you to detect that capabilities

https://pkg.go.dev/github.com/gookit/color#IsSupport256Color

The simplest would be to use this 

https://pkg.go.dev/github.com/muesli/termenv#DefaultOutput

Then call ColorProfile

https://pkg.go.dev/github.com/muesli/termenv#Output.ColorProfile

_Originally posted by @ccoVeille in https://github.com/hengyoush/kyanos/pull/184#discussion_r1887335214_

**Comment by hengyoush** [comment]
Thanks, I'll submit a pr later.
