### ISSUE TITLE
When filtering traffic by pod-name, if the pod cannot be found, display a message to notify the user.

### ISSUE THREAD

**Issue by hengyoush** [hengyoush/kyanos#205]
**Is your feature request related to a problem? Please describe.**
1. Currently on display a error log like: `can not find any running pod by name xxx`, we can add a message to notify the user to check  Kyanos is whether running on the same machine where the pod is located.
2. Add this case to faq docs.

**Describe the solution you'd like**
Add a message to notify the user to check  Kyanos is whether running on the same machine where the pod is located.

**Describe alternatives you've considered**

**Additional context**

**Comment by XmchxUp** [comment]
I think the error message should be more general.

it just needs to add in the FAQ that only local containers are supported.

**Comment by hengyoush** [comment]
> I think the error message should be more general.
> 
> 
> 
> it just needs to add in the FAQ that only local containers are supported.

I agree with you.
