### ISSUE TITLE
Add an e2e test to verify the `--comm` option works fine

### ISSUE THREAD

**Issue by hengyoush** [hengyoush/kyanos#212]
**Is your feature request related to a problem? Please describe.**
Add an e2e test to verify the `--comm` (filter by process name) option works fine

**Describe the solution you'd like**
1. Add a bash script file in `testdata/` which contains the main test logic. (like this one: `test_docker_filter_by_pid.sh`), including two cases:
    1. target process start , then kyanos start , expected kyanos can watch  the target process's network.
    2. kyanos start, then target process start,  expected kyanos can watch  the target process's network.

3. Add a step in workflow : .github/workflows/test.yml which executes the test script file in 1.

**Comment by spencercjh** [comment]
Can a simple Python HTTP server be started directly (not in a Docker container) in this e2e test?

![image](https://github.com/user-attachments/assets/7926f6b8-16d1-4f13-b430-f990cbf38059)
![image](https://github.com/user-attachments/assets/39b63b62-4dee-4ad8-a1a5-464f796e8c6c)
![image](https://github.com/user-attachments/assets/0a03c3d6-3510-46a1-846e-520d10bb7430)

I need to simulate my local operation in the test.

AM I RIGHT?

**Comment by spencercjh** [comment]
You haven't started this work yet, have you?

**Comment by hengyoush** [comment]
> You haven't started this work yet, have you?

No, I haven't.

> Can a simple Python HTTP server be started directly (not in a Docker container) in this e2e test?

ok.

@spencercjh

**Comment by spencercjh** [comment]
I looked at the source code and the filtering of processes is done in `SetupAgent` -> `LoadBPF` -> `setAndValidateParameters`, and this call link is only executed once when the program starts. The range of processes filtered is only a snapshot of what is running at the time and does not dynamically select emerging processes as the program runs. This makes it difficult to use `--comm` to filter `curl` processes for #212. 

It looks like `--comm` is not designed for one-off processes like `curl` but server proc. So the second test sub-task is unrealizable now.

> kyanos start, then target process start, expected kyanos can watch the target process's network.

Also, the current implementation of `--`comm is not very user-friendly. It only supports filtering something like the output of `ps —o comm`, which I could extend to support `ps —o cmd`.

@hengyoush

**Comment by hengyoush** [comment]
> I looked at the source code and the filtering of processes is done in SetupAgent -> LoadBPF -> setAndValidateParameters, and this call link is only executed once when the program starts. The range of processes filtered is only a snapshot of what is running at the time and does not dynamically select emerging processes as the program runs. This makes it difficult to use --comm to filter curl processes for https://github.com/hengyoush/kyanos/issues/212.

Actually, Kyanos knows when a process starts. After a process starts, it checks if the comm parameter matches the process name. If they match, it updates the filterPidMap in the kernel, bpf progs use filterPidMap to filter event by pid.

Look source code at: setAndValidateParameters(line: 292 ~ 309)

**Comment by spencercjh** [comment]
> > I looked at the source code and the filtering of processes is done in SetupAgent -> LoadBPF -> setAndValidateParameters, and this call link is only executed once when the program starts. The range of processes filtered is only a snapshot of what is running at the time and does not dynamically select emerging processes as the program runs. This makes it difficult to use --comm to filter curl processes for #212.
> 
> Actually, Kyanos knows when a process starts via eBPF tracepoint(sched_process_exec). After a process starts, it checks if the comm parameter matches the process name. If they match, it updates the filterPidMap in the kernel, bpf progs use filterPidMap to filter event by pid.
> 
> Look source code at: setAndValidateParameters(line: 292 ~ 309)

Looks like something went wrong with my local test. I'll carry on.

**Comment by hengyoush** [comment]
> Also, the current implementation of --comm is not very user-friendly. It only supports filtering something like the output of ps —o comm, which I could extend to support ps —o cmd.

Nice.

**Comment by spencercjh** [comment]
> > > I looked at the source code and the filtering of processes is done in SetupAgent -> LoadBPF -> setAndValidateParameters, and this call link is only executed once when the program starts. The range of processes filtered is only a snapshot of what is running at the time and does not dynamically select emerging processes as the program runs. This makes it difficult to use --comm to filter curl processes for #212.
> > 
> > 
> > Actually, Kyanos knows when a process starts via eBPF tracepoint(sched_process_exec). After a process starts, it checks if the comm parameter matches the process name. If they match, it updates the filterPidMap in the kernel, bpf progs use filterPidMap to filter event by pid.
> > Look source code at: setAndValidateParameters(line: 292 ~ 309)
> 
> Looks like something went wrong with my local test. I'll carry on.

The HTTPS protocol cannot be used when testing with curl. When using HTTP, we can see HTTP responses with 301.

**Comment by hengyoush** [comment]
The first case "target process start, then kyanos start, expected kyanos can watch the target process's network." , you may not be able to use curl as it will terminate very quickly. Therefore, a server process might be needed for testing. @spencercjh

**Comment by spencercjh** [comment]
> The first case "target process start, then kyanos start, expected kyanos can watch the target process's network." , you may not be able to use curl as it will terminate very quickly. Therefore, a server process might be needed for testing. @spencercjh

Thanks for the explanation. 😭 🙏
