### ISSUE TITLE
http url matching can support prefix matching or regular matching

### ISSUE THREAD

**Issue by macbobo** [hengyoush/kyanos#218]
**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by spencercjh** [comment]
https://github.com/hengyoush/kyanos/blob/main/agent/protocol/http.go#L260-L267

We need to enhance this part of the user namespace code and I can do this. ✌️

**Comment by hengyoush** [comment]
> https://github.com/hengyoush/kyanos/blob/5663995f93ae4ccf7071df6f708f34abe2e7d68a/agent/protocol/http.go#L260-L267
> 
> We need to enhance this part of the user namespace code and I can do this. ✌️

Go ahead!

**Comment by spencercjh** [comment]
Can we implement path-matching logic similar to the nginx `location`? For example `--path="~ \.php$"`, `--path="^~ /assets/"`, `--path=/api`

reference: 

- https://nginx.org/en/docs/http/ngx_http_core_module.html?#location
- https://www.uptimia.com/learn/nginx-location-priority-explained

![image](https://github.com/user-attachments/assets/9f71555b-5709-4322-9340-a2cddf673933)

![image](https://github.com/user-attachments/assets/963b654f-5043-4c17-8cb6-e0dc1f45859b)


@hengyoush @macbobo

**Comment by hengyoush** [comment]
I wonder if supporting regex or simple wildcard matching might be more accessible? Not everyone may be familiar with Nginx's matching syntax. @spencercjh

**Comment by hengyoush** [comment]
> I thought about this too ...... but I didn't know what syntax to use for the match rule in `--path`, so I found the Nginx `location`.

The standard regular expressions should be enough, I guess.

**Comment by spencercjh** [comment]
> > I thought about this too ...... but I didn't know what syntax to use for the match rule in `--path`, so I found the Nginx `location`.
> 
> The standard regular expressions should be enough, I guess.

A similar scenario is the label syntax in promQL, which can use `=` and `~=` to distinguish between strict and regular matches. Obviously, we can't do that right now, so what I'm asking is whether we need to rack our brains and use only one `--path` argument with some syntax (like `--path=~ \/api\/\w*`, `--path=/api/books`) to achieve multiple matches.

If there is no better solutions, it's easy to think of introducing new parameters (e.g. `--path_regex`, `--path_prefix`) to do regular/prefix filtering.

**Comment by hengyoush** [comment]
Of course you can add a parameter.
