### ISSUE TITLE
Add version command

### ISSUE THREAD

**Issue by hengyoush** [hengyoush/kyanos#229]
**Is your feature request related to a problem? Please describe.**
Add a version command.

**Comment by spencercjh** [comment]
Is your release process to create a Release on GitHub? (which then triggers an existing workflow)

I can modify an existing workflow so that the release's version number (tag) is passed in as `-ldflags="-X"` when building a Go program as output for the `kyanos version`.

**Comment by hengyoush** [comment]
Yes, I'm using Gorealser. You can find its configuration file in the root path of the project. And the workflow is release.yml
