### ISSUE TITLE
get error "FATA[0000] Attach failed: creating perf_kprobe PMU (arch-specific fallback for "dev_queue_xmit"): token __x64_dev_queue_xmit: not found: no such file or directory, functions: [{kprobe/dev_queue_xmit DevQueueXmit}] "

### ISSUE THREAD

**Issue by luojiyin1987** [hengyoush/kyanos#47]
**Describe the bug**

**To Reproduce**
`sudo kyanos`

**Expected behavior**

**Screenshots**
`FATA[0000] Attach failed: creating perf_kprobe PMU (arch-specific fallback for "dev_queue_xmit"): token __x64_dev_queue_xmit: not found: no such file or directory, functions: [{kprobe/dev_queue_xmit DevQueueXmit}] `

**Desktop (please complete the following information):**
 - OS:  Host OS pve-manager/8.1.3/b46aac3b42da5d15 ,     vm   Ubuntu 24.04.1 LTS

**Additional context**

**Comment by hengyoush** [comment]
Thank you for your reply! I will fix this issue soon.

**Comment by hengyoush** [comment]
> **Describe the bug** A clear and concise description of what the bug is.
> 
> **To Reproduce** Steps to reproduce the behavior: `sudo kyanos`
> 
> **Expected behavior**
> 
> **Screenshots** `FATA[0000] Attach failed: creating perf_kprobe PMU (arch-specific fallback for "dev_queue_xmit"): token __x64_dev_queue_xmit: not found: no such file or directory, functions: [{kprobe/dev_queue_xmit DevQueueXmit}] `
> 
> **Desktop (please complete the following information):**
> 
> * OS:  Host OS pve-manager/8.1.3/b46aac3b42da5d15 ,     vm   Ubuntu 24.04.1 LTS
> 
> **Additional context** Add any other context about the problem here.

Fixed, please download 1.3.2 and retry.

**Comment by luojiyin1987** [comment]
It is ok

**Comment by WaterStop** [comment]
May I ask what the reason for this bug is and how to fix it? I have also encountered the same problem

**Comment by hengyoush** [comment]
> May I ask what the reason for this bug is and how to fix it? I have also encountered the same problem

Please report a bug in another issue. @WaterStop
