### ISSUE TITLE
centos7.9 5.4版本运行会卡主 无任何输出

### ISSUE THREAD

**Issue by noovertime7** [hengyoush/kyanos#52]
**Describe the bug**
centos7.9 5.4版本运行会卡主 无任何输出，内核版本： 5.4.278-1.el7.elrepo.x86_64
执行`  sudo ./kyanos watch http` 无任何输出，执行`./kyanos stat`时，在按ctrl c退出时会有一行日志打印
**Screenshots**
![image](https://github.com/user-attachments/assets/ddcbf011-f5e7-41a6-a4fa-6121fddfb086)
![image](https://github.com/user-attachments/assets/2dd1930d-e4c6-40ce-9352-8295583cbc76)

**Comment by noovertime7** [comment]
![image](https://github.com/user-attachments/assets/307b500d-5eda-4966-b1a6-92a7f53d461d)

**Comment by hengyoush** [comment]
感谢反馈，这个问题会尽快修复。

**Comment by hengyoush** [comment]
（这个问题大概率是btf文件没找对的bug）
也可以尝试下这个步骤：
1. 下载5.4.28-200.el7.x86_64.btf.tar.xz文件并且解压：wget https://ghp.ci/github.com/aquasecurity/btfhub-archive/blob/main/centos/7/x86_64/5.4.28-200.el7.x86_64.btf.tar.xz
2. 然后使用 kyanos stat http --btf /path/to/5.4.28-200.el7.x86_64.btf 再试下
@noovertime7

**Comment by noovertime7** [comment]
![image](https://github.com/user-attachments/assets/5cf68f7d-3152-4cb0-a6fd-e7221398ed7f)
有输出了，但是也是只有按ctrl c的时候有反应

**Comment by hengyoush** [comment]
可以加上 -i 5，这样每5s输出一次

**Comment by noovertime7** [comment]
stat http 可以了，watch mysql 一直是空白的

**Comment by noovertime7** [comment]
![image](https://github.com/user-attachments/assets/488d18f9-34ce-4780-8bdc-12d98a1a2feb)

**Comment by hengyoush** [comment]
确定有MySQL流量吧
